language: rust
rust: nightly

before_install: set -e

install:
  - rustup component add rustfmt

script:
  - cargo fmt --all -- --check
  - cargo check

after_script: set +e

notifications:
  email:
    on_success: never